### PR TITLE
Media Migration

### PR DESCRIPTION
**Pull request by Dwza**
Added the hint to call the media migration after downloading them. Otherwise they wont be visible.

### CODE REVIEW

**Comment by teiling88** [comment]
Hey @Dwza,
I think we can replace this:
```
wget -O test_images.zip http://releases.s3.shopware.com/test_images.zip
```
with this: 
```
wget -O test_images.zip http://releases.s3.shopware.com/test_images_since_5.1.zip
```

Please update your pr and squash your commits.

Thanks!

**Comment by teiling88** [comment]
thanks for your contribution :-)

**Comment by snooops** [comment]
To make this clean - could you @teiling88 fix this by yourself ;)

**Comment by teiling88** [comment]
Closed during inactivity. Fixed with: https://github.com/shopwareLabs/shopware-vagrant/pull/41

**Pull request closed without merging**
