### PR TITLE
Vagrant-Hostmanager, Grunt

### PR DESCRIPTION
**Pull request by fboes**
Proposing some minor changes to add support for [Vagrant Hostmanager](https://github.com/devopsgroup-io/vagrant-hostmanager) and port forwarding to allow Grunt & [LiveReload](http://livereload.com/) to work out of the box. ;)

### CODE REVIEW

**Comment by teiling88** [comment]
Hey @fboes,
thanks for your contribution. I merged 97d1dae and f41176f from your pull request.

The Vagrant-Hostmanager is not installed by default so we don't need an integration of it for your base box at the moment.

Greetings

**Comment by fboes** [comment]
@teiling88 Glad to contribute. Actually I think the settings for Vagrant-Hostmanager won't do anything dangerous if there is no Vagrant-Hostmanager present - but the settings are a nice addition if the Vagrant-Hostmanager _is_ installed. 

Right now I cannot test this, but maybe someone else can… ;)

**Comment by teiling88** [comment]
> Actually I think the settings for Vagrant-Hostmanager won't do anything dangerous if there is no Vagrant-Hostmanager present

See the error message below _without_ Vagrant-Hostmanager :-)

> There are errors in the configuration of this machine. Please fix
the following errors and try again:
> Vagrant:
> * Unknown configuration section 'hostmanager'.

Without Vagrant-Hostmanager the Vagrantfile is invalid.

**Comment by fboes** [comment]
:( Too bad. Nevermind, it still was a pleasure to contribute. :)

**Comment by teiling88** [comment]
It was a pleasure! :)

**Pull request closed without merging**
