### PR TITLE
fix problem when switching php version

### PR DESCRIPTION
**Pull request by bestit-tkellner**
use /home/vagrant/bin/changephp_5.6 to change php version.

### CODE REVIEW

**Comment by bcremer** [comment]
Please make sure a fresh installation runs without errors.

With your patch the following leads to an error:

```
vagrant destroy && vagrant up
```

Error:

```
TASK [apache : Install Apache/PHP] *********************************************
failed: [default] (item=[u'libapache2-mod-php5.6', u'php5.6-cli', u'php5.6-curl', u'php5.6-gd', u'php5.6-mysql', u'php5.6-mbstring', u'php5.6-simplexml', u'php5.6-xml', u'php5.6-zip', u'php5.6-apcu', u'libapache2-mod-php7.0', u'php7.0-cli', u'php7.0-curl', u'php7.0-gd', u'php7.0-mysql', u'php7.0-mbstring', u'php7.0-simplexml', u'php7.0-xml', u'php7.0-zip', u'php7.0-apcu', u'libapache2-mod-php7.1', u'php7.1-cli', u'php7.1-curl', u'php7.1-gd', u'php7.1-mysql', u'php7.1-mbstring', u'php7.1-simplexml', u'php7.1-xml', u'php7.1-zip', u'php7.1-apcu', u'php-xdebug']) => {"failed": true, "item": ["libapache2-mod-php5.6", "php5.6-cli", "php5.6-curl", "php5.6-gd", "php5.6-mysql", "php5.6-mbstring", "php5.6-simplexml", "php5.6-xml", "php5.6-zip", "php5.6-apcu", "libapache2-mod-php7.0", "php7.0-cli", "php7.0-curl", "php7.0-gd", "php7.0-mysql", "php7.0-mbstring", "php7.0-simplexml", "php7.0-xml", "php7.0-zip", "php7.0-apcu", "libapache2-mod-php7.1", "php7.1-cli", "php7.1-curl", "php7.1-gd", "php7.1-mysql", "php7.1-mbstring", "php7.1-simplexml", "php7.1-xml", "php7.1-zip", "php7.1-apcu", "php-xdebug"], "msg": "No package matching 'php7.0-apcu' is available"}
	to retry, use: --limit @/vagrant/ansible/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=11   changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I will investigate if the vagrant setup can be tested via Travis-CI or another build-service.

**Comment by bestit-tkellner** [comment]
hey @bcremer,
i have this problem too ;-)

But this is not a problem with this pr. You get this error with all previous commits too.

The reason is an error on the ondrej php apt repository. The build for php7.0-apcu is failed:
https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by bcremer** [comment]
@bestit-tkellner good catch :+1: 

It seems like the package was renamed to `php-apcu`. I'll fix that on master.

**Comment by bestit-tkellner** [comment]
that's not necessary. The build problem is fixed and php7.0-apcu is available again.

**Comment by bcremer** [comment]
Merged with commit: https://github.com/shopwareLabs/shopware-vagrant/commit/ace45542a20369faba2ccb7c707b0e3726d4733a

Thanks!

**Pull request closed without merging**
